// ============================================================
// [教學] prisma.config.ts —— Prisma「指令列工具」的設定檔
//
// 這個檔案只在你手動下指令時被讀取（migrate / generate / studio），
// API 跑起來之後完全用不到它。
//
// 為什麼連線字串要寫兩次？因為使用者有兩種：
//   CLI（你在終端機下指令）   → 讀這個檔案
//   執行期（NestJS 服務本身） → 讀 src/prisma/prisma.service.ts
// 兩者是不同的 process，各自讀自己的設定，schema.prisma 因此不必寫 url。
//
// 注意：這個檔案在專案根目錄，必須列在 tsconfig.build.json 的 exclude，
// 否則編譯輸出路徑會跑掉（docs/chapters/ch00-環境建置.md 的「踩到的坑」第一條）。
// 以後在根目錄新增任何 .ts 檔都要留意這件事。
//
// 下一站：test/health.e2e-spec.ts（怎麼自動驗證上面整條路都通）
// ============================================================

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

// [教學] 這行會把 .env 的內容讀進 process.env。
// NestJS 那邊由 ConfigModule 負責做同一件事，但 CLI 沒有 Nest，
// 所以要自己 import 一次。
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  // [教學] 告訴 CLI 去哪找模型定義、把 migration 的 SQL 檔存到哪。
  // migrations 資料夾會在 Ch1 第一次跑 migrate 時自動出現，且要進版控 ——
  // 它是資料庫結構的變更歷史，正式環境靠它重建同樣的表。
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
